app:
  aaa: 123
  maps:
    -
      cachePath:  d://mapcache
      tileUrl: https://api.tiles.mapbox.com/v4/mapbox.streets/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw
      capabilityUrl: 123
      featureInfoUrl: 111
    -
      cachePath:  d://mapcache1
      tileUrl: https:/Q.
      capabilityUrl: 234
      featureInfoUrl: 345